### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Aslemammad** [kitten/use-editable#1]
Hey @kitten, I really loved useEditable, And I'm reading its magical source as a junior, Do you have any idea that I can add to the project or some todos.
Thanks.

**Comment by kitten** [comment]
Hiya 👋

Happy you're interested in helping out! That reminds me, I have to add some more standard documents to the repo;

Anyway, I currently believe the API is pretty complete for a first version, so I haven't put down any ideas for new features quite yet.

But creating new examples in CodeSandbox could help more people get started quickly with the hook! For instance you could try to create an example that adds auto-suggestions to an editable. They don't have to be complex but an example that looks at `onChange`, sees how the text ends, and maybe shows a Dropdown overlay, outside of the editable markup, would be an interesting demo!

What do you think? 🙌

**Comment by Aslemammad** [comment]
I loved that idea. I'll work on them, And I'll share it here.

**Comment by Aslemammad** [comment]
Can I create it with the example you made on codesandbox, I mean can I work with the Highlight tokens?

**Comment by Aslemammad** [comment]
#2
