### ISSUE TITLE
Dropdown-example

### ISSUE THREAD

**Issue by Aslemammad** [kitten/use-editable#2]
I've been working on a dropdown example, and I made it. I hope you like it and accept it. I'll be so happy with your opinions. [codesandbox](https://codesandbox.io/s/use-editable-dropdown-p3cee)

**Comment by Aslemammad** [comment]
And if it's good enough to be in the README, let me know, because I wanted to edit the README by myself, because I think it's a good haktoberfest thing.

**Comment by kitten** [comment]
This is great! There are some issues around keyhandling still influencing the outer editor, but I'd love to add this to the readme :+1: I think it's also missing the actual selection of the suggestion which could just be done using the returned `useEditable` function I think.
